name: Setup pnpm
description: Setup pnpm with cache
runs:
  using: "composite"
  steps:
    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - uses: pnpm/action-setup@v2.2.3
      with:
        version: 7.1.2
    - name: Install Dependencies
      run: pnpm install
      shell: bash
