name: Lint

# Inspiration:
# https://github.com/alexdiliberto/ember-transformicons/blob/master/.github/workflows/ci.yml
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - master

env:
  CI: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: volta-cli/action@v1

    - name: Install
      run: yarn install

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: volta-cli/action@v1

    - name: Install
      run: yarn install

    - name: ESLint
      run: yarn lint:js

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: volta-cli/action@v1

    - name: Install
      run: yarn install

    - name: Docs
      run: yarn lint:docs

jobs:
  docs-js:
    name: Docs (JS)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: volta-cli/action@v1

    - name: Install
      run: yarn install

    - name: Docs (JS)
      run: yarn lint:docs-js

jobs:
  commits:
    name: Commit Messages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: volta-cli/action@v1

    - name: Install
      run: yarn install

    - name: Commit Messages
      run: yarn commitlint
