name: Lint

# Inspiration:
# https://github.com/alexdiliberto/ember-transformicons/blob/master/.github/workflows/ci.yml
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - master

env:
  CI: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: volta-cli/action@v1

    - run: yarn install
    - run: yarn lint:js

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: volta-cli/action@v1

    - run: yarn install
    - run: yarn lint:docs

  docs-js:
    name: Docs (JS)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: volta-cli/action@v1

    - run: yarn install
    - run: yarn lint:docs-js

  commits:
    name: Commit Messages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: volta-cli/action@v1

    - run: yarn && volta install @commitlint/cli
    - run: git log --pretty=format:%B master...$GITHUB_SHA | commitlint
