name: Lint

# Inspiration:
# https://github.com/alexdiliberto/ember-transformicons/blob/master/.github/workflows/ci.yml
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - master

env:
  CI: true

jobs:
  lint:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1

    - run: yarn install
    - run: yarn lint:js

  docs:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1

    - run: yarn install
    - run: yarn lint:docs

  docs-js:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: Docs (JS)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1

    - run: yarn install
    - run: yarn lint:docs-js

  commits:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: Commit Messages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: volta-cli/action@v1
    - uses: wagoid/commitlint-github-action@v4.1.5


    # - run: yarn && volta install @commitlint/cli
    # - run: |
    #     git log --pretty=format:%B master...$GITHUB_REF
    #     echo "shoving the above into commitlint"
    #     git log --pretty=format:%B master...$GITHUB_REF | commitlint
